### ISSUE TITLE
Allow blocking of app integration (e.g. Twitter)

### ISSUE THREAD

**Issue by maxxyme** [ketanbhatt/block-slack-users#1]
Hi,

Why not also block bots?
The admins if my company installed the Twitter integration: http://slack.com/apps/A0F7XDW93-twitter
which re-posts tweets to some channels (but's it's quite annoying).
And your extension doesn't block these messages.

**Comment by ketanbhatt** [comment]
Hey, So there are already [extensions that can block bots](https://chrome.google.com/webstore/detail/slack-bot-filter/blephhkggdennbfmdcjmlfimedknghfc) while there were none that could block users, so I built one 👻 

I shall add this feature in future though, in 2 weeks.

**Comment by maxxyme** [comment]
Thanks for pointing me this extension out, but unfortunately, it doesn't seem to (still) work (probably broken due to a Slack update in March... never fixed until now!)

**Comment by ketanbhatt** [comment]
Hey @maxxyme 
I have updated the extension and now it can block bots as well 👻

**Comment by maxxyme** [comment]
Just tested... nicely works!!! Good job! ;)
