### ISSUE TITLE
the extension doesn't appear to work with the most recent slack updates

### ISSUE THREAD

**Issue by rboyer** [ketanbhatt/block-slack-users#3]
I think slack updated the CSS/HTML for their webapp. This blocking extension no longer works.

**Comment by hfavisado** [comment]
I noticed that they're using `c-message__sender_link` now instead of `data-member-id` (/src/inject/inject.js)

**Comment by SoulRiderX** [comment]
Yes, ten days later still not working.

**Comment by dballing** [comment]
Can a version with this fix please be uploaded to the Chrome Web Store at some point soon?

**Comment by ketanbhatt** [comment]
Hey @dballing, I will put one up tonight for sure. Thank you for the patience.

**Comment by Hellmark** [comment]
Any idea when this update will make it to the Chrome Webstore. Version there is from February 12th, and not functional.

**Comment by ketanbhatt** [comment]
Hey @Hellmark I havent been able to find time to work on this. I will update timelines in a week :)

**Comment by ketanbhatt** [comment]
Hey, @Hellmark @dballing I have updated the version on the chrome store. You will now be able to hide both messages on the main window as well as threads. 
Sorry for the delay here.

Happy Slacking 💃

**Comment by ketanbhatt** [comment]
The update will start reflecting in the store within 60 minutes.
